server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Douaesb/MicroBank_Config.git
          default-label: main
          clone-on-start: true
