server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Douaesb/MicroBank.git
          search-paths:
            - "customer-service"
            - "account-service"
            - "gateway-service"
            - "discovery-service"
            - "config-service"
          clone-on-start: true
